version: '3'
networks:
  yolo:
    driver:bridge
services:

  mongodb:
    image: mongo:latest
    networks:
      - yolo
    volumes:
      -mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - yolo
    ports:
      - 3001:3001
    depends_on:
      - mongodb

  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    networks:
      - yolo
    ports:
      -3000:3000
    depends_on:
      - backend



  

