version: '3'

services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - yolo
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    networks:
      - yolo
    ports:
      - 5000:5000
    environment:
        PORT : 5000
        MONGODB_URI: mongodb://mongodb_data:27017
        DB_NAME: yolomy
        NAME: truyolo

    depends_on:
      - mongodb

  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    networks:
      - yolo
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  mongodb_data:

networks:
  yolo:
    driver : bridge



  

