---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
  tags:
    - common

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
  tags:
    - common

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes 